apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-one-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /first
        pathType: Prefix
        backend:
          service:
            name: flaskone
            port:
              number: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: flaskone
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: flaskone


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskone
  template:
    metadata:
      labels:
        app: flaskone
    spec:
      containers:
        - name: flaskone
          image: kostasloykas/assignment2:latest
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
          env:
            - name: MESSAGE
              value: "This is the first service!"
