apiVersion: batch/v1
kind: Job
metadata:
  name: myjob 
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: mycontainer
        image: ubuntu:20.04
        command: ["/myconfigvolume/config.sh"]
        volumeMounts:
          - name: myconfigvolume
            mountPath: "/myconfigvolume"
      volumes:
        - name: myconfigvolume
          configMap:
            name: myconfigmap
            defaultMode: 0511
  backoffLimit: 0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  config.sh: |
    #!/bin/bash
    apt-get update
    apt-get install git -y
    apt-get install make -y
    apt-get install -y wget
    wget https://github.com/gohugoio/hugo/releases/download/v0.124.0/hugo_extended_0.124.0_linux-amd64.deb
    dpkg --install hugo_extended_0.124.0_linux-amd64.deb
    git clone "https://github.com/chazapis/hy548"
    cd hy548 && git submodule init && git submodule update && make all