apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-one-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /first
        pathType: Prefix
        backend:
          service:
            name: flaskone
            port:
              number: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: flaskone
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: flaskone


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskone
  template:
    metadata:
      labels:
        app: flaskone
    spec:
      containers:
        - name: flaskone
          image: kostasloykas/assignment2:latest
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: MESSAGE
              value: "This is the first service!"


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flaskone-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaskone
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
