apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-two-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /second
        pathType: Prefix
        backend:
          service:
            name: flasktwo
            port:
              number: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: flasktwo
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: flasktwo


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasktwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasktwo
  template:
    metadata:
      labels:
        app: flasktwo
    spec:
      containers:
        - name: flasktwo
          image: kostasloykas/assignment2:latest
          env:
            - name: MESSAGE
              value: "This is the second service!"
