name: Build and Push Docker Image (Assignment 1)

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          push: true
          tags: kostasloykas/assignment1:latest
